### PR TITLE
Add cod model from ss3models

### PR DESCRIPTION
**Pull request by k-doering**
The cod model from ss3sim/ss3models was maintained more than the model in ss3sim and wanted this more current version in ss3sim. These models are still for SS 3.24.

### CODE REVIEW

**Comment by k-doering** [comment]
I forgot that those models were used for tests and therefore apt to break.

**Comment by kellijohnson** [comment]
Sorry @k-doering, I thought that I commented on this pull request earlier, but I don't see it here.  You can use devtools to check what example is failing with the new model.
```
library(devtools)
ss3simpath <- "c:/ss3sim" # Change this for your computer
check(cran = FALSE)
```

**Comment by k-doering** [comment]
Okay, I will do that, thanks, Kelli!

**Comment by k-doering** [comment]
Looks like the issues now are due to changing the model to a 3.30 one, and all the associated problems that pop up with that. Maybe it makes sense to not merge update_cod into update_3.3? What do you think, @kellijohnson ?

**Comment by kellijohnson** [comment]
In the best-case scenario we would:
(1) rename this 3.3 cod model to gadid or something
(2) keep the 3.24v of the cod model that you brought over from ss3sim/ss3models
(3) update the tests and examples to work with the 3.24v cod so that nothing is broken
(4) merge the unbroken branch with two models, i.e., gadid and cod, into update3.3
Or, we can just keep everything right here and start working on getting this 3.3 model to work. For example, first we need to add the proper executables to the bin folder.

**Comment by k-doering** [comment]
Okay, I didn't realize we wanted to keep an active 3.24 model. I'm going to cancel this pull request, work in a different branch so that the 3.3 model isn't overwriting the 3.24 model, and try to troubleshoot using the 3.24 model.

**Comment by kellijohnson** [comment]
This plan is fine. You can also just do it in this branch. We won't keep the 3.24 for all of eternity, I just don't want to merge branches together until they are useable. So the closing of each branch represents a ss3sim package that can be used rather than just a handful of commits.

**Comment by k-doering** [comment]
Got it, that makes sense. I'm going to stick with using a separate branch because I'm not git-savvy enough yet to understand how to roll back commits, so starting fresh seems easiest.

**Pull request closed without merging**
