### PR TITLE
build, #323: add workflows to style and run devtools::document

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Reusable workflows are now available to run [styler::style_pkg()](https://github.com/nmfs-stock-synthesis/workflows/blob/main/.github/workflows/style-r-code.yml) and [devtools::document](https://github.com/nmfs-stock-synthesis/workflows/blob/main/.github/workflows/update-roxygen-docs.yml) !! 

How they currently work is that they each run the given function, then open a pull request with the changes (if any) to the branch from which the workflow was started.

Currently, I set the build triggers to run weekly, as well as a manual trigger for testing purposes. I'm not sure how well other triggers will work, given a commit is made in the process (e.g., if the workflow runs on all pushes to main, it will open a PR; then when the PR is merged it will run the workflow again???)

### CODE REVIEW

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA , forgot to say, let me know any thoughts you have. I've tested on SSMSE, but am happy to tweak. We can then add to r4ss as well, if it works for @iantaylor-NOAA .

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA thanks for these additions, I am very excited about not having to run `document()`. Do you think that we should run styler prior to merging in this pull request given that it hasn't been run on the package yet?

**Comment by kellijohnson-NOAA** [comment]
I also wonder if there is something that you can put in the commit message or something that you can put in the workflow to reduce the recursive nature of being run if pushed to master. Like if the commit is from a bot don't run the workflow for the latter? Not sure, just trying to think of options. [Recursive workflows are slightly talked about here on stackoverflow](https://stackoverflow.com/questions/68549751/github-action-to-lint-after-commit-in-previous-step) but I am sure there are more resources out there.

**Comment by iantaylor-NOAA** [comment]
Nice work @k-doering-NOAA. I'm happy to have this be part of r4ss, but maybe it's worth tweaking here (or at SSMSE) first.

**Comment by k-doering-NOAA** [comment]
Good point @kellijohnson-NOAA  - would you prefer these to run on pushes to main, for example?

You are right, I think we could add an if statement to look for some key words in the last commit message, perhaps, similar to what [the approach in this r-lib workflow](https://github.com/r-lib/actions/blob/fd9a09a778173fe57e2801815a36d73473f8bba7/examples/pr-commands.yaml#L11)

**Comment by kellijohnson-NOAA** [comment]
I am honestly not sure what the best approach is. I will look at some other more high-profile packages to see what is seen as "good practice".

**Comment by k-doering-NOAA** [comment]
I just added an if statement if the name of the function referenced in the commit msg (styler::style_pkg or devtools::document) is referenced in the last commit msg...  so I think we could try out running on every commit to main, if desired.

Let me know if you learn any more about best practices, I haven't seen a lot of workflows like this one out there, so IDK if anything is established or not.

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA. The following two things came to mind before we merge this in:

1. The only thing different I found was using styler on a pull request before merging rather than on main. I think the main point of this is to alert those pushing to the code where their proposal differed from best practices with respect to the linter so that potentially in the future there are less changes needed. I know that there was some talk of this on [r4ss](https://github.com/r4ss/r4ss/issues/516). It could be seen as confusing, judgmental, or uninviting to critique someone's coding style when they are contributing, but hopefully people won't see it this way as style guides increase and the use of automated code increases as well. I am fine with leaving it as is with pushing on main.
2. Should we run `styler` before merging in this pull request. I haven't done this yet with ss3sim and I think that there are going to be a lot of changes 😲.

**Comment by k-doering-NOAA** [comment]
1. Yes, IDK if the point is to style in order to help folks maybe learn from it or just to make it a more "hidden" process that happens so the code is more readable. I'm also not sure if styling PRs before merging into main will cause more conflicts?
2.  I agree, yes. I can do this if you would like!

**Comment by kellijohnson-NOAA** [comment]
I never thought about merge conflicts b/c of styling, good thought. And, regarding (2), yes that would be great.

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA should we merge this in now that you ran `styler()`?

**Comment by k-doering-NOAA** [comment]
Yes, sure!

**Pull request merged**
