### PR TITLE
Deprecate casefiles and associated functions

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
See #288 . This pull request deprecates (i.e., makes defunct) using casefiles to specify scenarios. Instead, a dataframe should be provided to `simdf` in `run_ss3sim`. See the vignettes for more details, or use `setup_scenerio_defaults()` to get a basic example of the dataframe that can be modified.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
I found a few things using a global search for 'case' that need to be completed before we merge this.
1. The vignettes need to be updated to remove all references to case files.
2. `sample_calcomp` references cases
3. `setup_scenarios` references cases
4. `ss3sim_base` references cases

**Comment by k-doering-NOAA** [comment]
I am done making changes - just will need to remember to re-render the vignettes to host on github pages once this is merged into master. @kellijohnson-NOAA , feel free to merge when you are ready!

**Comment by kellijohnson-NOAA** [comment]
Great, thanks for being so timely. I will merge once the test pass.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA , I'm not sure why 1 of the checks was canceled (maybe waiting too long for a machine?), but I don't think we need to worry about it since all the other checks passed.

**Comment by kellijohnson-NOAA** [comment]
Thank you @k-doering-NOAA.

**Pull request merged**
