### PR TITLE
Standardize

### PR DESCRIPTION
**Pull request by cstawitz**

### CODE REVIEW

**Comment by kellijohnson** [comment]
@seananderson I am currently making a few changes to this one and then maybe you can glance over it.

**Comment by kellijohnson** [comment]
I am unsure if we should use ```...``` in ```standardize_bounds``` to pass ```verbose = FALSE``` to ```change_lo_hi```

**Comment by cstawitz** [comment]
That's a good idea Kelli- I like the option to leave it on for testing but
it would be good to be able to turn it off later.

On Fri, Jan 30, 2015 at 11:02 AM, Kelli Johnson <notifications@github.com>
wrote:

> I am unsure if we should use ... in standardize_bounds to pass verbose =
> FALSE to change_lo_hi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/pull/198#issuecomment-72252125>.
>



-- 
Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by seananderson** [comment]
I made some small changes. I also edited the example so that it runs by default. This means it automatically gets checked whenever the package is checked and the user can easily run the example. Two things:

1. Christine, can you take a look at what I did to the call to `SS_changepars()`? I'm not sure what the original intention was there, but I couldn't get it to work with a simple case where the user passes a control file name in the current working directory. But, maybe I'm missing something.

2. When I run the example that uses the cod model, I get warnings. Can you look into those and make sure everything is fine?

Thanks!

```R
library(devtools)
load_all()
dev_example("standardize_bounds")
```

Output:

```
Loading ss3sim
Running examples in standardize_bounds.Rd --------------------------------------------------------
Warning message:
longer object length is not a multiple of shorter object length
Warning message:
longer object length is not a multiple of shorter object length
parameter names in control file matching input vector 'strings' (n=3):
[1] "Wtlen_1_Fem"       "Mat_slope_Fem"     "Eggs/kg_inter_Fem"
These are the ctl file lines as they currently exist:
   LO HI      INIT   PRIOR PR_type SD PHASE             Label Linenum
45  0  3  6.80e-06 6.8e-06      -1  0    -1       Wtlen_1_Fem      45
48 -2  2 -2.76e-01 0.0e+00      -1  0    -3     Mat_slope_Fem      48
49 -3  3  1.00e+00 0.0e+00      -1  0    -3 Eggs/kg_inter_Fem      49
line numbers in control file (n=3):
[1] 45 48 49
Warning message:
longer object length is not a multiple of shorter object length

wrote new file to em.ctl with the following changes:
    oldvals   newvals oldphase newphase             comment
1  6.80e-06  6.80e-06       -1       -1       # Wtlen_1_Fem
2 -2.76e-01 -2.76e-01       -3       -3     # Mat_slope_Fem
3  1.00e+00  1.00e+00       -3       -3 # Eggs/kg_inter_Fem
wrote new file to em.ctl
```

**Comment by kellijohnson** [comment]
The messages you were getting in the above example are because there is currently no way to squash output from ```SS_changepars```. I have wrapped it now in ```capture.output``` along with changed the way ```grep``` works inside the function by removing punctuation and using ```ignore.case = TRUE```. The function seems to work now even if you pass it the cod OM ctl file and the flt EM ctl file. I also added functionality to ```estimate```, so if we decide to use ```standardize_bounds``` within ```change_e``` that you can specify if it should change the estimation phase or not. 

@seananderson I am curious if you can run the example now without errors? 
```r
library(devtools)
load_all()
dev_example("standardize_bounds")
```
Worked for me, but why it is not passing the Travis CI build? I don't really understand what Travis Cl is to be honest.

**Comment by seananderson** [comment]
For Travis CI, if you click on the 'Details' link beside the failed build [you'll see a log](https://travis-ci.org/ss3sim/ss3sim/builds/49033535) of what it's doing. Each time it's cloning the package from GitHub, installing R (!), installing the ss3sim package along with dependencies, and running `R CMD check`. So, you'll get the same test by running `check()` locally. The 'CI' stands for continuation integration (meaning continuous testing) if that wasn't clear. What it does is set by this file: https://github.com/ss3sim/ss3sim/blob/master/.travis.yml  You can create that via a devtools function.

The example runs locally for me with the GitHub version of r4ss but fails on the CRAN version (which is what Travis CI will install). So, I guess we need to add `\dontrun{}` around the example for now. Word is that CRAN is now testing `donttest{}`, so you need `\dontrun{}`. I'll make that change now and sync.

**Comment by taylori** [comment]
I modified `SS_changepars` to turn off cat statements with `verbose=FALSE` as suggested by @kellijohnson (https://github.com/r4ss/r4ss/issues/46). While I was doing this, I went ahead and merged functionality of `change_lo_hi` from @cstawitz into `SS_changepars`. In theory, call to `change_lo_hi` within `standardize_bounds` can now be replaced by `SS_changepars`, but I haven't tried it.
Changes are at: https://github.com/r4ss/r4ss/commit/759e9528d91e0f2d03152a4350137d25692028be

**Comment by cstawitz** [comment]
Thanks Sean, Kelli and Ian. I'm trying to test it with replacing 'SS_changepars' but I'm getting the following warnings and errors: 'Warning: restarting interrupted promise evaluation
Warning: internal error -3 in R_decompress1
Error: lazy-load database 'P' is corrupt'

Replacing the call to 'change_lo_hi' with 'SS_changepars' isn't crucial though, so we should probably merge as-is for now?

**Comment by seananderson** [comment]
Try restarting R.

**Comment by cstawitz** [comment]
OK it should be fixed now.

**Comment by seananderson** [comment]
Once we're resolved the directory issue, do you want to merge this into master, @kellijohnson?

**Comment by kellijohnson** [comment]
I will test and try to merge this afternoon.

**Comment by kellijohnson** [comment]
Changed to ```file.path``` within the function and fixed an error regarding missing argument in last call to ```SS_changepars```. I plan on testing this tomorrow with the models in the www.github/ss3sim/growth_models repository, if all goes well I will merge.

**Comment by cstawitz** [comment]
@kellijohnson I am guessing you didn't merge this? Do you want me to take care of it as I need to make a change to the function?

**Comment by kellijohnson** [comment]
I was not going to merge it until I tested it out on the ss3models. I can merge it now or you can edit it here, just let me know.

**Comment by cstawitz** [comment]
OK, I am just trying to get it up to date before I make my change since it
has gotten pretty far behind master. I can test it out after that on the
ss3models too if you'd like since I think you have a lot more on your plate
than I do.

On Fri, Feb 13, 2015 at 10:18 AM, Kelli Johnson <notifications@github.com>
wrote:

> I was not going to merge it until I tested it out on the ss3models. I can
> merge it now or you can edit it here, just let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/pull/198#issuecomment-74299990>.
>



-- 
Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by kellijohnson** [comment]
@cstawitz it is now in master, can you please look into the warning of "unused arguments" in ```standardize_bounds``` of ```newlos = newlos, newhis = newhis```. Can they be removed now that we use ```SS_changepars```?

**Comment by cstawitz** [comment]
Kelli, somehow that deleted all of the changes we've made to standardize in
master. How do we get them back?

On Fri, Feb 13, 2015 at 10:45 AM, Kelli Johnson <notifications@github.com>
wrote:

> @cstawitz <https://github.com/cstawitz> it is now in master, can you
> please look into the warning of "unused arguments" in standardize_bounds
> of newlos = newlos, newhis = newhis. Can they be removed now that we use
> SS_changepars?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/pull/198#issuecomment-74304354>.
>



-- 
Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by cstawitz** [comment]
K, I think I've got it back from the history.

On Fri, Feb 13, 2015 at 10:53 AM, Christine Stawitz <cstawitz@uw.edu> wrote:

> Kelli, somehow that deleted all of the changes we've made to standardize
> in master. How do we get them back?
>
> On Fri, Feb 13, 2015 at 10:45 AM, Kelli Johnson <notifications@github.com>
> wrote:
>
>> @cstawitz <https://github.com/cstawitz> it is now in master, can you
>> please look into the warning of "unused arguments" in standardize_bounds
>> of newlos = newlos, newhis = newhis. Can they be removed now that we use
>> SS_changepars?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ss3sim/ss3sim/pull/198#issuecomment-74304354>.
>>
>
>
>
> --
> Christine Stawitz
> Quantitative Ecology and Resource Management
> Box 355020
> University of Washington
> Seattle, WA 98195
> cstawitz@uw.edu
>
> http://students.washington.edu/cstawitz/
>



-- 
Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Pull request merged**
