### PR TITLE
Standardize

### PR DESCRIPTION
**Pull request by cstawitz**
Added a function (standardize_bounds) to check that the EM and OM control file initial values are the same and modify the EM control file bounds to a standard percentage of the EM init values. The other R script is included to show how the function may be used and facilitate testing.

### CODE REVIEW

**Comment by seananderson** [comment]
Thanks Christine. Can you make a few small changes before I merge this in?

1. Move the test script somewhere outside the package functions (say in `ss3sim/tests`). Otherwise the package won't build.

2. Change the function argument names to use underscores just to match the style of the rest of the package.

3. Add a title in the Roxygen comments. The first line will be the title the next chunk will be the description even without a tag. See for example https://github.com/ss3sim/ss3sim/blob/master/R/get_sigma.r

4. Ideally, add a little example with `@examples`. E.g. https://github.com/ss3sim/ss3sim/blob/master/R/change_maturity.R   But don't worry about that part if it seems like too much trouble.

5. Run `devtools::document()` to create the documentation (`.Rd` files) and `devtools::check()` to make sure the package still passed R CMD check.

You can just push these changes to the same branch and they'll show up in the same pull request.

Thanks!

**Comment by colemonnahan** [comment]
Christine, this will be a very useful function. Also don't forget to put yourself as the @author so we know who to ask if it stops working (and you get credit!)

**Comment by cstawitz** [comment]
Thanks all - I will make these updates tomorrow afternoon.

On Mon, Jan 12, 2015 at 8:04 PM, Cole Monnahan <notifications@github.com>
wrote:

> Christine, this will be a very useful function. Also don't forget to put
> yourself as the @author <https://github.com/author> so we know who to ask
> if it stops working (and you get credit!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/pull/190#issuecomment-69692623>.
>



-- 
Christine Stawitz
Quantitative Ecology and Resource Management
Box 355020
University of Washington
Seattle, WA 98195
cstawitz@uw.edu

http://students.washington.edu/cstawitz/

**Comment by cstawitz** [comment]
I made all of the the suggested changes! Thanks for the feedback.

**Comment by seananderson** [comment]
Thanks Christine! I made a few small formatting changes, which you can see above. 

Bonus points for updating all the .Rd files with the newest version of roxgyen2 (4.1.0). (Which means we should all be using the latest roxygen2 and devtools from now on.)

**Pull request merged**
