### PR TITLE
Run styler

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Adds in changes from running styler on the ss3sim source code.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
Any chance you know how to implement the tidyverse "double indent" instead of "function indent" styling? Although, I think @iantaylor-NOAA prefers the function indent b/c it works with emacs better than double indentations. The thing I don't like about function indent is that if you change the name of the function then the indentation changes; also, it seems like so much wasted real estate. I am fine with keeping it as is, I am more curious than anything.

**Comment by k-doering-NOAA** [comment]
I can check into this tomorrow, there may be an option! I just used the default, which is probably tidyverse style. Easy to run it again!

**Comment by k-doering-NOAA** [comment]
Hi Kelli, it looks like there are [ways to customize styler](https://styler.r-lib.org/articles/customizing_styler.html) , but I can't find the exact solution to implement double indent style.

Also, thinking about this more, I think just sticking to a standard style is best, even if we don't like every aspect of it. If we run styler frequently, it's not a big deal if you don't get the new indenting right when the function name changes.

**Comment by kellijohnson-NOAA** [comment]
Thanks for looking @k-doering-NOAA and I agree that default behavior here is probably better than monkeying with things.

**Pull request merged**
