### PR TITLE
add initF functionality

### PR DESCRIPTION
**Pull request by peterkuriyama**
I modified the change_f and change_data to add the ability to handle an Initial F value in the control file

### CODE REVIEW

**Comment by peterkuriyama** [comment]
#302

**Comment by k-doering-NOAA** [comment]
Thanks for adding this @peterkuriyama!I think this code only adds equilibrium catch to the first fleet?

I think it would be helpful if this also could work if multiple fleets have catch or if there are muliple seasons in the model. But, perhaps if you need this quickly it should just be merged in now and generalized at a later date if needed? What are your thoughts?

Also, I should say @kellijohnson-NOAA is the ss3sim maintainer, but is usually off on Fridays, so I don't think she will have a chance to look until next week.

**Comment by kellijohnson-NOAA** [comment]
@peterkuriyama sorry for the delay wrt reviewing this pull request. I plan on completing it today.

**Comment by k-doering-NOAA** [comment]
Hi @peterkuriyama , @kellijohnson-NOAA incorporated the PR into commit https://github.com/ss3sim/ss3sim/commit/ce9bd1c58d6da6594b8756820274b54ae296f3c3 , which generalizes the initF functionality suggested here. Note that there is a detailed commit msg describing the changes made and how the feature works.

I'm not sure if the 2 of you have touched base, but if not, maybe you could test out using ss3sim from the `main` branch (see #305 ) and see if initF is working for you ? If so, I think we can close this without merging.

**Comment by k-doering-NOAA** [comment]
Closing this pull request to delete the development branch, as we are now using the main branch instead (see #305 ). @peterkuriyama , if you want to open a new PR, feel free to do so, merging it instead into ss3sim:main .

**Pull request closed without merging**
