### PR TITLE
Pmatch

### PR DESCRIPTION
**Pull request by kellijohnson**
Fixed partial matching error for sampling functions. for the FltSvy column. The partial matching warning is now removed and the package is compatible with older versions of r4ss, which used Fleet for weight at age data. Package is up to date with newest documentation but does not pass ``check(CRAN = TRUE)`` because the ``sample_wtatage`` function has undocumented arguments and other errors for documentation in some of the sampling functions.

### CODE REVIEW

**Comment by seananderson** [comment]
Thanks Kelli!

I believe it's passing R CMD check but with messages and warnings (or so says Travis CI). That's fine for now until we submit to CRAN. There are lots of little messages and warnings to fix. The big issue is does it fail R CMD check, because then we can't install the package.

**Comment by kellijohnson** [comment]
@seananderson should I open a new branch with a better name for the fixes I am currently working on or should I just keep working in this one?

**Comment by seananderson** [comment]
Probably open a new one. This one is closed and merged. You should be able to start a new branch from where you are and all changes will come with you.

**Comment by kellijohnson** [comment]
okay sounds great, will do.

**Pull request merged**
