### PR TITLE
Fix weight comps

### PR DESCRIPTION
**Pull request by k-doering-NOAA**
Changes need to fix ss3sim so it can work with the new functionality in `r4ss::SS_tune_comps`, as well as some changes to `r4ss::SS_readctl_3.30`

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA for this.
What do you think about moving the normalizepath call to get_bin() rather than after the fact. My thought is that if it is needed here it is probably also needed when other functions use it? Or would it be better to add a switch to get_bin() that allows you to normalize it. I just like to think that the functions within ss3sim provide the output needed rather than needing to directly manipulate the returned object.

**Comment by k-doering-NOAA** [comment]
Thanks for looking over the changes, @kellijohnson-NOAA! Your comment made me realize the call to `normalizePath()` was unnecessary - it was something I added in while trying to debug and then forgot to remove. I just pushed a commit to get rid of it. 

But I agree with your general philosophy that functions should produce output that is useful without another function being immediately called!

**Comment by kellijohnson-NOAA** [comment]
Great, so once this passes we can merge right? Also, could you perhaps provide a couple of notes on why the linux tests weren't passing. Just to help for future problems that we might encounter. I not very well versed in linux, so I think it would be helpful to document issues you encounter that makes Windows focused developers like myself aware of things that we are doing that are incompatible.

**Comment by k-doering-NOAA** [comment]
Yes, it should be good to merge if the checks on travis pass!

The issue was actually with `r4ss::run_SS_models`; the issues were:

1. there was some code that appended `./` to the front of Linux paths. To run ss in the same folder, calling "./ss" on the command line makes sense; however, when you have a relative or absolute path (say ~/bin/ss), then "./~/bin/ss" would be the path created, which doesn't work. This isn't a linux/mac specific problem, but the code had an if statement to only do this on linux/mac.
2. `file.info()` returns an exe component on windows, but it doesn't on Linux and Mac. I didn't know this and wrote code that use this function. We really just wanted to know whether the binary existed in a certain place, so I used `file.exists()` instead in r4ss/r4ss@9e72f45, which turned out to be a cleaner solution.

**Comment by kellijohnson-NOAA** [comment]
Perfect. Thanks for the info. Can you please merge when checks are complete. I may be offline for the majority of the rest of the day.

**Pull request merged**
