### PR TITLE
delete the CompReport.sso files since can be huge and not needed

### PR DESCRIPTION
**Pull request by colemonnahan**
Hi all, the CompReport.sso files can be REALLY large for the conditional age-at-length data rich scenarios (75MB not uncommon). I added a couple of lines to delete these two files from the OM and EM **during** the simulation, to help save on disk space for large numbers of iterations.

As far as I can tell we can't turn the production of these files off, and we don't use them for anything. So I wouldn't mind merging this feature into the master branch. If one needs to look at a file for an individual run they can always rerun it manually.

Anyone disagree with this update?

### CODE REVIEW

**Comment by seananderson** [comment]
That sounds good to me. If no one else has objections I'll merge it in.

**Comment by Kotkot** [comment]
Sounds good to me too.

**Comment by juanlvalero** [comment]
Sounds good to me too, I don't think either of the 3 papers uses the
CompReport.sso anyways
Juan

**Comment by taylori** [comment]
I see that get_results.r has the input NoCompOK=TRUE which allows the
reading of output without the CompReport.sso file.

I will noted that in an applied assessment context it would be crazy to
estimate growth and NOT look at the fit to the length and age data, for
which you would require the CompReport.sso files.
However, since nobody is going to be looking at all those fits anyway, I
don't have a problem with discarding those files.  Nevertheless, you might
consider setting it up so that CompReport.sso is saved for only the first
few iterations such that you could take a look at model fits for a few
cases with each case. You could also rerun a couple cases, but that seems
like more work and doubtful that anyone would do it.
-Ian

**Pull request merged**
